//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_Service_1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Login_itSoap")]
    public interface Login_itSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login_i", ReplyAction="*")]
        Console_Service_1.ServiceReference2.Login_iResponse Login_i(Console_Service_1.ServiceReference2.Login_iRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login_i", ReplyAction="*")]
        System.Threading.Tasks.Task<Console_Service_1.ServiceReference2.Login_iResponse> Login_iAsync(Console_Service_1.ServiceReference2.Login_iRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Login_iRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login_i", Namespace="http://tempuri.org/", Order=0)]
        public Console_Service_1.ServiceReference2.Login_iRequestBody Body;
        
        public Login_iRequest() {
        }
        
        public Login_iRequest(Console_Service_1.ServiceReference2.Login_iRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Login_iRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int password;
        
        public Login_iRequestBody() {
        }
        
        public Login_iRequestBody(string username, int password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Login_iResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login_iResponse", Namespace="http://tempuri.org/", Order=0)]
        public Console_Service_1.ServiceReference2.Login_iResponseBody Body;
        
        public Login_iResponse() {
        }
        
        public Login_iResponse(Console_Service_1.ServiceReference2.Login_iResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Login_iResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Login_iResult;
        
        public Login_iResponseBody() {
        }
        
        public Login_iResponseBody(bool Login_iResult) {
            this.Login_iResult = Login_iResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Login_itSoapChannel : Console_Service_1.ServiceReference2.Login_itSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Login_itSoapClient : System.ServiceModel.ClientBase<Console_Service_1.ServiceReference2.Login_itSoap>, Console_Service_1.ServiceReference2.Login_itSoap {
        
        public Login_itSoapClient() {
        }
        
        public Login_itSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Login_itSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Login_itSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Login_itSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Console_Service_1.ServiceReference2.Login_iResponse Console_Service_1.ServiceReference2.Login_itSoap.Login_i(Console_Service_1.ServiceReference2.Login_iRequest request) {
            return base.Channel.Login_i(request);
        }
        
        public bool Login_i(string username, int password) {
            Console_Service_1.ServiceReference2.Login_iRequest inValue = new Console_Service_1.ServiceReference2.Login_iRequest();
            inValue.Body = new Console_Service_1.ServiceReference2.Login_iRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Console_Service_1.ServiceReference2.Login_iResponse retVal = ((Console_Service_1.ServiceReference2.Login_itSoap)(this)).Login_i(inValue);
            return retVal.Body.Login_iResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Console_Service_1.ServiceReference2.Login_iResponse> Console_Service_1.ServiceReference2.Login_itSoap.Login_iAsync(Console_Service_1.ServiceReference2.Login_iRequest request) {
            return base.Channel.Login_iAsync(request);
        }
        
        public System.Threading.Tasks.Task<Console_Service_1.ServiceReference2.Login_iResponse> Login_iAsync(string username, int password) {
            Console_Service_1.ServiceReference2.Login_iRequest inValue = new Console_Service_1.ServiceReference2.Login_iRequest();
            inValue.Body = new Console_Service_1.ServiceReference2.Login_iRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Console_Service_1.ServiceReference2.Login_itSoap)(this)).Login_iAsync(inValue);
        }
    }
}
